tasks:
  - init: |
      apt update
      apt upgrade -y
      apt install -y sudo
      groupadd -r pufferpanel || true
      mkdir -p /var/lib/pufferpanel
      docker volume create pufferpanel-config
      docker create --name pufferpanel -p 8080:8080 -p 5657:5657 \
        -v pufferpanel-config:/etc/pufferpanel \
        -v /var/lib/pufferpanel:/var/lib/pufferpanel \
        -v /var/run/docker.sock:/var/run/docker.sock \
        --restart=on-failure pufferpanel/pufferpanel:latest
      docker start pufferpanel
      docker exec pufferpanel /pufferpanel/pufferpanel user add --name arthuzin --email 123@gmail.com --password 123456 --admin

  - init: |
      git init
      git add .
      git commit -m "Initial commit"
      git remote add origin <URL_DO_SEU_REPOSITORIO>
      git push -u origin master

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5657
    onOpen: ignore
