tasks:
  - init: |
      apt update
      apt upgrade
      apt install -y sudo
      mkdir -p /var/lib/pufferpanel
      docker volume create pufferpanel-config
      docker create --name pufferpanel -p 8080:8080 -p 5657:5657 \
        -v pufferpanel-config:/etc/pufferpanel \
        -v /var/lib/pufferpanel:/var/lib/pufferpanel \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -e USERNAME=arthuzin \
        -e EMAIL=123@gmail.com \
        --restart=on-failure pufferpanel/pufferpanel:latest
      docker start pufferpanel
      docker exec pufferpanel /pufferpanel/pufferpanel user add $USERNAME $EMAIL 123456 123456 y

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5657
    onOpen: ignore
