image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo apt-get update && sudo apt-get upgrade -y
      sudo apt-get install -y docker.io
      mkdir -p /var/lib/pufferpanel
      docker volume create pufferpanel-config
      docker create --name pufferpanel -p 8080:8080 -p 5657:5657 -v pufferpanel-config:/etc/pufferpanel -v /var/lib/pufferpanel:/var/lib/pufferpanel -v /var/run/docker.sock:/var/run/docker.sock --restart=on-failure pufferpanel/pufferpanel:latest
      docker start pufferpanel
      echo -e "arthuzin\n123@gmail.com\n123456\n123456\ny" | docker exec -i pufferpanel /pufferpanel/pufferpanel user add
    command: echo "PufferPanel is running, and user is set up."

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5657
    onOpen: ignore

# Use this to point to a Dockerfile which pre-installs any necessary tools
# This Dockerfile should be crafted to include Docker itself if you plan to use it within the Gitpod environment
image:
  file: .gitpod.Dockerfile
